#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Postcode
version:      0.11
version_from: lib/Geo/Postcode.pm
installdirs:  site
requires:
    DBD::SQLite:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
